### ISSUE TITLE
Is tilecube actually based on TMS?

### ISSUE THREAD

**Issue by tmcw** [CartoDB/tilecubes#4]
https://github.com/CartoDB/tilecubes/blob/master/2.0/spec.md

This references TMS as the spec for tilecube tile coordinates. Are tilecube coordinates really TMS, or are they XYZ, like OpenStreetMap? It's relatively rare for people to do the 0-at-the-bottom-style for tile coords.

**Comment by timrobertson100** [comment]
They are XYZ like OSM, Google etc.

**Comment by tmcw** [comment]
Closing because of no response for several months. Feel free to reopen if this issue will be fixed.
