### ISSUE TITLE
Choosing one name

### ISSUE THREAD

**Issue by fdansv** [CartoDB/tilecubes#8]
As it's been pointed out by @sobier [here](https://github.com/CartoDB/docs/pull/552/files#diff-31d318f7d002d74cbf12f3f425aadbfeR24), there are way too many variations of the name _tilecubes_, like "TorqueTiles", "datacubes" or "layercubes". Maybe we should settle on one term to rule them all?

My personal preference: let's do away with all `*cube` variations and stick with Torque tiles (without the camelCase). If we stick to  tilecubes, I think we're just going to keep using permutations of `[tile, layer, data, cubes]`.

@javisantana @andrewxhill @rochoa

**Comment by andrewxhill** [comment]
up to you guys! :)

**Comment by fdansv** [comment]
OK, as agreed with @csobier from now on we'll be using "Torque tiles" in docs and future references.
